- .github/gbs.conf
- .github/workflows/build.yml
- lwnode/code/escargotshim/test/cctest/test-api.cc
- lwnode/code/escargotshim/test/cctest/v14_test_3.cc
Change-Id: Ib815c49feb3d08a27774dfbb8a5511480f66a3ae
> chore: Add build actions

- .github/workflows/build.yml
> chore: Update build action for PR

- deps/node-bindings/include/node_bindings.h
- deps/node-bindings/node_bindings.gyp
- deps/node-bindings/src/gmainloop_node_bindings.cc
> feat: add node-bindings

- README.md
- docs/lwnode.md
> doc: add lwnode.md

- README.md
- docs/App-db-service.md
- docs/Build.md
* Also fix an example in the guide
> doc: fix broken links in docs

- .github/workflows/actions.yml
- README.md
> doc: add badges in README

- configure.py
- deps/node/configure.py
- deps/node/tools/gyp_node.py
> chore: add more verbose logs

- deps/node-bindings/src/gmainloop_node_bindings.cc
- modules/packages/device-api/CMakeLists.txt
- modules/packages/device-api/src/DeviceAPIModule.cpp
- modules/packages/device-api/src/Extension.h
- modules/packages/device-api/src/TizenDeviceAPILoaderForEscargot.h
- modules/packages/device-api/test/bluetooth.js
- modules/packages/device-api/test/volume.js
- add volume and bluetooth test
> feat(packages): set idler callback in device-api

- packaging/lwnode.spec
This mostly includes:
- Adding .so to the rpm if `lib_type` is shared
- ~~Building the devel package as optional~~ Remove building the devel package
> chore: update the packaging spec

- common.gypi
> chore: add tizen conditional defines

- deps/tizen.gyp
- escargotshim.gyp
> chore: add dlog configs to shim

- configure.py
> chore: add an exception scope for running gyp

- .github/workflows/actions.yml
- modules/packages/packaging/lwnode-modules.manifest
- modules/packages/packaging/lwnode-modules.spec
- packaging/lwnode.spec
- To install modules on target, change to sub packages
> chore: add modules build packages

- .github/workflows/actions.yml
`check_tidy.py` has compatibility issues on python3. 
> chore: add lint cc

- README.md
- docs/App-db-service.md
- docs/App-service.md
- docs/Build.md
- docs/Debugger.md
- docs/Framework.md
- docs/Spec.md
> doc: update documents

- deps/node/lib/internal/lwnode/setup.js
- deps/node/src/node_main_lw.cc
- include/lwnode/lwnode.h
- src/lwnode/lwnode.cc
> feat: add SystemInfo

- modules/packages/device-api/src/DeviceAPIModule.cpp
- modules/packages/device-api/test/bluetooth.js
- chage bluetooth test to finding devices
> fix(packages): fix error about WebAPIException in device-api

- README.md
- docs/Tizen-tpk-app.md
> doc: make tpk app guide

- deps/node/lib/internal/modules/cjs/loader.js
> feat: add node module path for Tizen

- README.md
- docs/lwnode-modules.md
- modules/packages/device-api/README.md
- modules/packages/gmain-loop/README.md
> doc: add modules guide

- README.md
- docs/Internal.md
- tools/release.sh
- tools/release_filter.txt
> chore: add release script

- deps/node/lib/internal/bootstrap/switches/is_main_thread.js
- deps/node/lib/internal/lwnode/setup.js
- deps/node/src/debug_utils-inl.h
- deps/node/src/debug_utils.cc
- deps/node/src/lwnode/aul-event-receiver.cc
- deps/node/src/lwnode/aul-event-receiver.h
- deps/node/src/node_process_methods.cc
- include/lwnode/lwnode.h
- src/api/utils/logger/logger-impl.cc
- src/api/utils/logger/logger-impl.h
- src/api/utils/logger/logger.cc
- src/api/utils/logger/logger.h
- src/lwnode/lwnode.cc
- feat: apply appID for dlog
- refactor: change StdOut to flush without a newline
> feat: bind lwnode logger

- deps/node/lib/internal/lwnode/memory.js
> feat: add memory threshold tracker

- deps/node/lib/internal/lwnode/memory.js
- deps/node/test/parallel/test-lwnode-memory-watcher.js
- docs/lwnode.md
> feat: add `PssSwap` memory usage on MemWatcher

- MAINTAINERS.md
> doc: update MAINTAINERS.md

- modules/packages/device-api/test/bluetooth.js
> fix(packages): fix bluetooth test

- src/api.cc
- tools/release.sh
- tools/release_filter.txt
- fix: use of vulnerable function 'strtok' 
- chore: update release_filter.txt
- chore: simplify get git-hash 
> fix: release issues

- deps/node/src/lwnode/aul-event-receiver.cc
Signed-off-by: Daeyeon Jeong <daeyeon.jeong@samsung.com>
> Fix static analysis defects

- .github/workflows/actions.yml
- deps/node/test/skip_tests.txt
- src/api/engine.h
- src/api/isolate.cc
- src/api/utils/sf-vector.h
> fix: prevent stack overflow errors for promise callback

- src/api-exception.cc
- src/api-handles.cc
- src/api/utils/logger/logger-impl.cc
> fix: support gcc13

- deps/node/src/node_crypto.cc
- packaging/lwnode.spec
> fix: fix build break when using openssl3

- deps/node/src/module_wrap.cc
- deps/node/src/node_messaging.cc
- src/api-environment.cc
- src/api/utils/logger/flags.cc
Signed-off-by: Daeyeon Jeong <daeyeon.jeong@samsung.com>
> fix: resolve static analysis defects

- deps/node/src/module_wrap.cc
- deps/node/src/node_messaging.cc
- src/api-environment.cc
- src/api/utils/logger/flags.cc
- https://github.com/Samsung/lwnode/pull/61
Signed-off-by: Daeyeon Jeong <daeyeon.jeong@samsung.com>
> [Backport] fix: resolve static analysis defects

- packaging/lwnode.spec
> chore: fix signing error in gbs

- modules/packages/device-api/src/TizenDeviceAPILoaderForEscargot.cpp
- modules/packages/device-api/src/TizenDeviceAPILoaderForEscargot.h
- include coding style modifications
> fix(packages): fix crash issue when running device-api

- deps/node/src/lwnode/aul-event-receiver.cc
Signed-off-by: Daeyeon Jeong <daeyeon.jeong@samsung.com>
> fix: capture `isEventReceiverRunning` by value

- deps/node/src/lwnode/aul-event-receiver.cc
- include/lwnode/lwnode.h
- modules/packages/device-api/CMakeLists.txt
- modules/packages/device-api/src/ExtensionAdapter.cpp
- modules/packages/device-api/src/TizenRuntimeInfo.cpp
- modules/packages/device-api/src/TizenRuntimeInfo.h
- modules/packages/packaging/lwnode-modules.spec
- src/lwnode/lwnode.cc
> feat(packages): handle GetRuntimeVariable in runtime function

- modules/packages/device-api/src/TizenRuntimeInfo.cpp
> fix(packages): fix privileges concat string

- deps/node-bindings/src/gmainloop_node_bindings.cc
> fix: fix g_source_unref use

- include/lwnode/lwnode.h
- modules/packages/device-api/CMakeLists.txt
- modules/packages/device-api/README.md
- modules/packages/device-api/src/Extension.cpp
- modules/packages/device-api/src/ExtensionManager.cpp
- modules/packages/device-api/src/ExtensionManager.h
- modules/packages/device-api/src/TizenDeviceAPILoaderForEscargot.cpp
- modules/packages/device-api/src/TizenDeviceAPILoaderForEscargot.h
- modules/packages/device-api/src/TizenInputDeviceKeyMap.h
- modules/packages/device-api/src/TizenInputDeviceManager.cpp
- modules/packages/device-api/src/TizenInputDeviceManager.h
- modules/packages/device-api/test/tvinputdevice.js
- modules/packages/packaging/lwnode-modules.spec
- src/api/isolate.cc
- src/api/isolate.h
- src/lwnode/lwnode.cc
- implement HandleRuntimeSyncMessage
- read input device from /dev/input/eventX
- handle key press and release event
- emit key event to JavaScript
- add test
> feat(packages): add tvinputdevice in device-api

- .github/workflows/actions.yml
> chore: update uplaod-artifact version
